/**
 * topics-data.js  –  Server-side copy of the 42-day topic schedule.
 * Contains only the fields needed for email notifications.
 */

export const TOPICS = [
  // Week 1: Getting Started
  { id:1,  day:1,  week:1, title:"What is GitHub Copilot?",                      subtitle:"Your AI Pair Programmer – Introduction & Overview",          difficulty:"Beginner",    audience:"both",      duration:"10 min", summary:"Understand what GitHub Copilot is, how it works under the hood with large language models, and why it's transforming how developers and testers write code.", keyPoints:["LLM-based AI trained on public GitHub repositories","Supports 30+ languages including Python, JS, TypeScript, Java, C#, Go","Available in VS Code, JetBrains, Visual Studio, Neovim, and CLI","Two main modes: inline completions and Copilot Chat","Requires a GitHub Copilot subscription (Individual, Business, or Enterprise)"], links:[{text:"GitHub Copilot Official Docs",url:"https://docs.github.com/en/copilot"},{text:"About GitHub Copilot",url:"https://docs.github.com/en/copilot/about-github-copilot/what-is-github-copilot"}] },
  { id:2,  day:2,  week:1, title:"Setting Up GitHub Copilot in VS Code",          subtitle:"Install, Authenticate & Configure for the First Time",       difficulty:"Beginner",    audience:"both",      duration:"15 min", summary:"Step-by-step guide to installing the GitHub Copilot extension in VS Code, authenticating with your GitHub account, and configuring basic settings.", keyPoints:["Install both 'GitHub Copilot' and 'GitHub Copilot Chat' extensions","Sign in via OAuth with your GitHub account","Verify activation via the Copilot icon in the status bar","Free tier available for verified students and OSS maintainers","Configure per-language enable/disable in VS Code settings"], links:[{text:"Setting Up Copilot in VS Code",url:"https://docs.github.com/en/copilot/managing-copilot/configure-personal-settings/installing-the-github-copilot-extension-in-your-environment"},{text:"Copilot Quickstart",url:"https://docs.github.com/en/copilot/quickstart"}] },
  { id:3,  day:3,  week:1, title:"Your First Code Suggestion",                    subtitle:"Experiencing Inline Completions in Action",                  difficulty:"Beginner",    audience:"both",      duration:"12 min", summary:"Write your first Copilot-assisted code. Learn how to trigger suggestions, read ghost text, and understand what makes a good prompt.", keyPoints:["Tab accepts a suggestion; Escape dismisses it","Alt+] / Alt+[ cycles through multiple suggestions","Comments are the most powerful prompt signal","Clear naming and types dramatically improve suggestion quality","Open 'Copilot Completions Panel' to see all alternatives at once"], links:[{text:"Getting Code Suggestions",url:"https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot"},{text:"Best Practices for Prompts",url:"https://docs.github.com/en/copilot/using-github-copilot/best-practices-for-using-github-copilot"}] },
  { id:4,  day:4,  week:1, title:"Understanding Ghost Text & Inline Completions",  subtitle:"How Copilot Generates and Ranks Suggestions",                difficulty:"Beginner",    audience:"both",      duration:"12 min", summary:"Dive deeper into how inline completions work — what context Copilot sees, how it ranks suggestions, and how to control when it triggers.", keyPoints:["Copilot sends prefix + suffix + neighboring files as context","Ctrl+Enter opens the completions panel with up to 10 alternatives","Ctrl+Right Arrow accepts a suggestion word by word","Neighboring open files influence suggestion quality","You can disable Copilot per-language without uninstalling"], links:[{text:"How Copilot Generates Suggestions",url:"https://docs.github.com/en/copilot/about-github-copilot/copilot-in-context"}] },
  { id:5,  day:5,  week:1, title:"GitHub Copilot Chat – Getting Started",          subtitle:"Conversational AI for Coding Questions",                     difficulty:"Beginner",    audience:"both",      duration:"15 min", summary:"Learn to use Copilot Chat — the conversational interface for asking coding questions, explaining code, fixing bugs, and generating boilerplate.", keyPoints:["Three surfaces: Chat Panel, Inline Chat (Ctrl+I), and Quick Chat","Ask questions in plain English — no special syntax required","Chat maintains conversation history for follow-up questions","Inline Chat edits code directly in the editor","Use 'New Chat' to reset context when switching tasks"], links:[{text:"Using Copilot Chat in VS Code",url:"https://docs.github.com/en/copilot/github-copilot-chat/copilot-chat-in-ides/using-github-copilot-chat-in-your-ide"}] },
  { id:6,  day:6,  week:1, title:"Copilot for Multiple Languages & File Types",    subtitle:"Python, JavaScript, TypeScript, Java, C#, and More",          difficulty:"Beginner",    audience:"both",      duration:"10 min", summary:"Explore how Copilot performs across different programming languages and file types, including configuration files, Markdown, and SQL.", keyPoints:["Best results with JS/TS, Python, Go, Java, C#","Works on YAML, JSON, Markdown, SQL, and Dockerfiles","Toggle Copilot per-language in VS Code settings","The more context (imports, types), the better the suggestions","SQL queries from natural language comments are particularly impressive"], links:[{text:"Supported Languages",url:"https://docs.github.com/en/copilot/about-github-copilot/supported-languages-in-github-copilot"}] },
  { id:7,  day:7,  week:1, title:"Week 1 Recap: Copilot Basics Cheat Sheet",       subtitle:"Essential Commands, Shortcuts & Mental Models",               difficulty:"Beginner",    audience:"both",      duration:"8 min",  summary:"A consolidated reference card for everything covered in Week 1 — shortcuts, key concepts, and the mental model for getting the most from Copilot.", keyPoints:["Tab = accept, Escape = reject, Alt+] = next suggestion","Ctrl+Enter = see all completions; Ctrl+I = inline chat","Always review Copilot's suggestions before accepting","Provide context through comments and good naming","Use Chat for 'why' questions, inline completions for 'what'"], links:[{text:"Full Keyboard Shortcut Reference",url:"https://docs.github.com/en/copilot/managing-copilot/configure-personal-settings/configuring-github-copilot-in-your-environment"}] },

  // Week 2: Core Features
  { id:8,  day:8,  week:2, title:"Mastering Inline Suggestions",                   subtitle:"Accepting, Rejecting & Cycling with Precision",              difficulty:"Beginner",    audience:"both",      duration:"12 min", summary:"Go beyond Tab-to-accept. Learn partial acceptance, cycling strategies, the completions panel, and how to guide Copilot with follow-up edits.", keyPoints:["Ctrl+Right for word-by-word acceptance","Ctrl+Enter opens a panel with 10 alternative completions","Iterative editing — accept, fix, let Copilot re-suggest","Reject suggestions for security-critical code paths","Cycling with Alt+] is faster than opening the completions panel"], links:[{text:"Getting Code Suggestions",url:"https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot"}] },
  { id:9,  day:9,  week:2, title:"Comment-Driven Development",                     subtitle:"Using Natural Language as Your Primary Input",               difficulty:"Beginner",    audience:"both",      duration:"15 min", summary:"Learn the art of writing descriptive comments that guide Copilot to generate exactly the code you need — the single most powerful Copilot technique.", keyPoints:["Describe the algorithm, not the implementation","Specify input types, output types, and edge cases in comments","Multi-step numbered comments produce the best structured code","Mention specific libraries to guide API usage","Comments are your primary way to communicate intent to Copilot"], links:[{text:"Prompting GitHub Copilot",url:"https://docs.github.com/en/copilot/using-github-copilot/prompt-engineering-for-github-copilot"}] },
  { id:10, day:10, week:2, title:"Copilot in the Terminal",                        subtitle:"AI-Powered Command Line Suggestions",                        difficulty:"Intermediate", audience:"both",      duration:"12 min", summary:"Use Copilot CLI to get AI-powered suggestions for shell commands, git workflows, and terminal tasks without leaving the command line.", keyPoints:["Use @terminal in Copilot Chat to get shell command help","Install gh copilot CLI extension for terminal-native AI","gh copilot suggest + explain are the key commands","Copilot understands the current directory context","Great for complex git, docker, and kubectl workflows"], links:[{text:"Using Copilot in the Terminal",url:"https://docs.github.com/en/copilot/github-copilot-in-the-cli/using-github-copilot-in-the-cli"}] },
  { id:11, day:11, week:2, title:"Slash Commands in Copilot Chat",                 subtitle:"/explain, /fix, /tests, /doc and More",                      difficulty:"Beginner",    audience:"both",      duration:"15 min", summary:"Master Copilot Chat slash commands — the power shortcuts that perform specific operations on your selected code with a single command.", keyPoints:["/explain – instant code explanation in plain English","/fix – AI-powered bug detection and correction","/tests – generate unit tests with a single command","/doc – auto-generate JSDoc/docstrings","Combine slash commands with natural language instructions"], links:[{text:"Slash Commands Reference",url:"https://docs.github.com/en/copilot/github-copilot-chat/copilot-chat-in-ides/using-github-copilot-chat-in-your-ide#slash-commands"}] },
  { id:12, day:12, week:2, title:"Context Variables: @workspace, @file, @vscode",  subtitle:"Giving Copilot the Right Scope",                             difficulty:"Intermediate", audience:"both",      duration:"15 min", summary:"Learn how to use @workspace, @file, #file, and @vscode context variables to scope your Copilot Chat questions precisely.", keyPoints:["@workspace searches your entire codebase for relevant context","#file references a specific file by path","@vscode answers VS Code configuration and feature questions","#selection references your current highlighted code","Combining context variables gives Copilot the precise scope it needs"], links:[{text:"Chat Context Variables",url:"https://docs.github.com/en/copilot/github-copilot-chat/copilot-chat-in-ides/copilot-chat-context"}] },
  { id:13, day:13, week:2, title:"Inline Chat vs. Chat Panel",                     subtitle:"Choosing the Right Interaction Surface",                     difficulty:"Beginner",    audience:"both",      duration:"10 min", summary:"Understand the difference between Inline Chat and the Chat Panel, when to use each, and how they complement each other in your workflow.", keyPoints:["Inline Chat (Ctrl+I) = targeted in-editor edits","Chat Panel (Ctrl+Alt+I) = persistent conversational assistant","Quick Chat = lightweight floating window for quick questions","Use Inline Chat for code actions, Chat Panel for architectural questions","Both share the same AI model and slash commands"], links:[{text:"Inline Chat",url:"https://docs.github.com/en/copilot/github-copilot-chat/copilot-chat-in-ides/using-github-copilot-chat-in-your-ide#using-copilot-inline-chat"}] },
  { id:14, day:14, week:2, title:"Week 2 Recap: Core Features Summary",            subtitle:"Master Reference for Everyday Copilot Use",                 difficulty:"Beginner",    audience:"both",      duration:"8 min",  summary:"Consolidated reference for all Week 2 core features — slash commands, context variables, chat surfaces, and comment-driven development patterns.", keyPoints:["Three chat surfaces for different interaction needs","Slash commands are the fastest path to common operations","@workspace unlocks codebase-wide intelligence","Comment-driven development is the most productive Copilot pattern","Always review and test — Copilot is a collaborator, not a compiler"], links:[{text:"Copilot Chat Docs",url:"https://docs.github.com/en/copilot/github-copilot-chat"}] },

  // Week 3: For Developers
  { id:15, day:15, week:3, title:"Writing Functions & Classes with Copilot",       subtitle:"Accelerating Development from Boilerplate to Logic",          difficulty:"Intermediate", audience:"developer", duration:"20 min", summary:"From simple utility functions to full class implementations — learn how to scaffold, complete, and refine code structures using Copilot.", keyPoints:["Define the interface/type before asking Copilot to implement it","Class comments describing dependencies dramatically improve suggestions","Use step-by-step numbered comments for complex function logic","Copilot handles builder, factory, and repository patterns very well","Always review edge case handling — Copilot may omit null checks"], links:[{text:"Getting Code Suggestions",url:"https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot"}] },
  { id:16, day:16, week:3, title:"Refactoring Code with Copilot",                  subtitle:"/simplify, /optimize, and Targeted Rewrites",                difficulty:"Intermediate", audience:"developer", duration:"18 min", summary:"Use Copilot to modernize legacy code, reduce complexity, improve readability, and apply design patterns through guided refactoring conversations.", keyPoints:["Select code + /simplify or /optimize for quick refactors","Describe the target pattern to get design pattern rewrites","Use chat for large refactors that span multiple methods","Always run tests after refactoring to catch regressions","Ask Copilot to explain its changes before accepting"], links:[{text:"Refactoring with Copilot",url:"https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-for-pull-requests/refactoring-code"}] },
  { id:17, day:17, week:3, title:"Generating Unit Tests Automatically",             subtitle:"From /tests to Full Test Suites in Minutes",                  difficulty:"Intermediate", audience:"developer", duration:"20 min", summary:"Let Copilot generate comprehensive unit tests for your functions and classes, covering happy paths, edge cases, and error scenarios.", keyPoints:["/tests generates unit tests for selected code instantly","Specify your test framework and mocking library in the prompt","Copilot detects the installed test framework from package.json/pom.xml","Use TDD: write test descriptions first, let Copilot implement bodies","Always verify edge cases and mock isolation in generated tests"], links:[{text:"Generating Unit Tests",url:"https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-for-testing"}] },
  { id:18, day:18, week:3, title:"Debugging with Copilot",                         subtitle:"Error Explanation, Root Cause Analysis & /fix",              difficulty:"Intermediate", audience:"developer", duration:"18 min", summary:"Use Copilot to understand error messages, trace root causes, and apply intelligent fixes — making debugging faster and more educational.", keyPoints:["/fix on selected code provides in-place bug fixes","Paste error messages + stack traces into Chat for root cause analysis","#terminalLastCommand references your latest terminal error","Describe expected vs. actual behavior for the best debugging help","Copilot explains why a bug occurs, not just how to fix it"], links:[{text:"Debugging with Copilot",url:"https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-for-debugging"}] },
  { id:19, day:19, week:3, title:"Auto-Generating Documentation",                  subtitle:"JSDoc, Docstrings & README Generation",                      difficulty:"Intermediate", audience:"developer", duration:"15 min", summary:"Generate JSDoc comments, Python docstrings, XML docs, and even README files automatically using Copilot's /doc command and chat.", keyPoints:["/doc generates language-appropriate documentation instantly","Specify the doc format: JSDoc, Google-style, NumPy-style","Ask for @example blocks to improve documentation usefulness","Copilot can generate READMEs, OpenAPI specs, and changelogs","Use @workspace to document multiple files at once"], links:[{text:"Generating Documentation",url:"https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-for-documentation"}] },
  { id:20, day:20, week:3, title:"API Integration Patterns with Copilot",          subtitle:"HTTP Clients, Authentication & Data Mapping",                 difficulty:"Intermediate", audience:"developer", duration:"20 min", summary:"Copilot accelerates API integration work — generating HTTP clients, auth headers, error handling, response mapping, and retry logic from simple descriptions.", keyPoints:["Describe the API base URL and auth method in your comment/prompt","Paste API response shapes to get accurate mapping functions","Ask for retry logic, timeout handling, and rate limiting explicitly","Copilot understands OAuth flows and can scaffold token refresh logic","OpenAPI specs pasted into Chat produce accurate service classes"], links:[{text:"Prompt Engineering",url:"https://docs.github.com/en/copilot/using-github-copilot/prompt-engineering-for-github-copilot"}] },
  { id:21, day:21, week:3, title:"Week 3 Recap: Developer Productivity Patterns",  subtitle:"From Scaffolding to Shipping — The Developer's Copilot Playbook", difficulty:"Intermediate", audience:"developer", duration:"10 min", summary:"A consolidated developer-focused reference covering the top Copilot patterns for writing, testing, documenting, debugging, and integrating APIs.", keyPoints:["Interface-first development maximizes Copilot suggestion quality","TDD + Copilot = describe tests in English, get implementations free","/fix + #terminalLastCommand = debugging superpowers","/doc + @workspace = auto-document entire modules","Paste API specs/schemas directly into Chat for accurate code generation"], links:[{text:"Copilot Best Practices",url:"https://docs.github.com/en/copilot/using-github-copilot/best-practices-for-using-github-copilot"}] },

  // Week 4: For Testers
  { id:22, day:22, week:4, title:"Test Case Generation from Requirements",         subtitle:"Turning User Stories into Test Plans",                        difficulty:"Intermediate", audience:"tester",    duration:"20 min", summary:"Transform user stories, acceptance criteria, and requirements documents into structured test cases using Copilot Chat.", keyPoints:["Paste acceptance criteria directly into Chat for instant test cases","Ask explicitly for positive, negative, boundary, and security cases","Copilot understands security anti-patterns like user enumeration","Ask for test priority and test data suggestions","Output in table format is ready for test management tools like Jira/TestRail"], links:[{text:"Copilot for Testing",url:"https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-for-testing"}] },
  { id:23, day:23, week:4, title:"BDD/Gherkin Scenarios with Copilot",             subtitle:"Feature Files, Cucumber, and Living Documentation",           difficulty:"Intermediate", audience:"tester",    duration:"18 min", summary:"Generate Gherkin feature files and step definitions for Cucumber, SpecFlow, or Behave using Copilot Chat and inline completions.", keyPoints:["Paste requirements and ask for complete feature files","Ask for Scenario Outlines to cover multiple data combinations","Generate step definitions by pasting the feature file","Copilot knows Cucumber (Java/JS), SpecFlow (.NET), and Behave (Python)","Ask for Background sections to reduce scenario duplication"], links:[{text:"Cucumber Docs",url:"https://cucumber.io/docs/guides/"}] },
  { id:24, day:24, week:4, title:"Automated Test Frameworks with Copilot",         subtitle:"Playwright, Cypress, Jest, Pytest & More",                    difficulty:"Intermediate", audience:"tester",    duration:"22 min", summary:"Set up and write automated tests across popular frameworks — Copilot generates page objects, test fixtures, mocks, and full test suites.", keyPoints:["Describe the UI flow in plain English — Copilot generates the selectors","Ask for Page Object Model classes for maintainable E2E tests","Specify mocking strategy: 'mock all external dependencies'","Copilot generates test fixtures and beforeEach/afterEach hooks","Use 'using [Framework]' to specify the exact tool"], links:[{text:"Testing with Copilot",url:"https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-for-testing"},{text:"Playwright Docs",url:"https://playwright.dev/docs/intro"}] },
  { id:25, day:25, week:4, title:"Performance & Load Test Script Generation",      subtitle:"k6, JMeter, Artillery & Locust",                              difficulty:"Advanced",    audience:"tester",    duration:"20 min", summary:"Generate load test scripts, performance benchmarks, and stress test scenarios using Copilot for k6, Apache JMeter, Artillery, and Locust.", keyPoints:["Describe load patterns (ramp-up, sustain, ramp-down) in natural language","Specify SLO assertions: p95, error rate, throughput","Ask for realistic user behavior scenarios with weighted flows","Copilot generates k6, Artillery, and Locust scripts well","Paste performance results and ask Copilot to identify bottlenecks"], links:[{text:"k6 Documentation",url:"https://k6.io/docs/"},{text:"Artillery Docs",url:"https://www.artillery.io/docs"}] },
  { id:26, day:26, week:4, title:"Security Testing with Copilot",                  subtitle:"OWASP Top 10, SQLi, XSS & Vulnerability Patterns",            difficulty:"Advanced",    audience:"tester",    duration:"22 min", summary:"Use Copilot to generate security test cases based on OWASP Top 10, identify vulnerable code patterns, and write automated security regression tests.", keyPoints:["Only test systems you own or have explicit authorization to test","Use /explain on suspect code to identify vulnerabilities","Ask Copilot to review code for OWASP Top 10 issues","Generate security regression tests to prevent regressions","Copilot knows OWASP patterns, SANS CWE, and common auth flaws"], links:[{text:"OWASP Top 10",url:"https://owasp.org/www-project-top-ten/"}] },
  { id:27, day:27, week:4, title:"Test Data Generation & Mocking",                 subtitle:"Faker, Factories, and Realistic Test Datasets",               difficulty:"Intermediate", audience:"tester",    duration:"18 min", summary:"Generate realistic test data factories, mock service implementations, and data seeding scripts using Copilot.", keyPoints:["Use @faker-js/faker (JS) or Faker (Python) — Copilot knows both","Specify relationships between data objects for realistic scenarios","Ask for factory functions with optional overrides for flexibility","MSW handlers generated from API specs produce accurate mocks","Generate both valid and invalid data sets for positive/negative tests"], links:[{text:"Faker.js Docs",url:"https://fakerjs.dev/"},{text:"Mock Service Worker",url:"https://mswjs.io/docs/"}] },
  { id:28, day:28, week:4, title:"Week 4 Recap: The Tester's Copilot Toolkit",    subtitle:"From Test Cases to Automation — The Complete QA Playbook",   difficulty:"Intermediate", audience:"tester",    duration:"10 min", summary:"A consolidated QA-focused reference for using Copilot across the full testing spectrum — from requirements to automation to security.", keyPoints:["Copilot covers the full QA spectrum: unit → E2E → performance → security","Paste requirements directly into Chat for instant test artifacts","BDD: requirements → Gherkin → step definitions with three prompts","Always specify the framework and mocking strategy in your prompt","Copilot is your always-available testing SME — but verify its output"], links:[{text:"Copilot for Testing",url:"https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-for-testing"}] },

  // Week 5: Advanced Features
  { id:29, day:29, week:5, title:"Custom Instructions & copilot-instructions.md",  subtitle:"Teaching Copilot Your Team's Conventions",                   difficulty:"Advanced",    audience:"both",      duration:"20 min", summary:"Configure persistent custom instructions that make every Copilot suggestion align with your team's coding standards, frameworks, and conventions.", keyPoints:[".github/copilot-instructions.md applies to all team members in the repo","Document your stack, naming conventions, and testing requirements","Personal instructions in VS Code settings apply across all repos",".prompt.md files create reusable task templates","Instructions reduce the need to repeat context in every prompt"], links:[{text:"Custom Instructions Docs",url:"https://docs.github.com/en/copilot/customizing-copilot/adding-repository-custom-instructions-for-github-copilot"}] },
  { id:30, day:30, week:5, title:"Prompt Engineering for GitHub Copilot",          subtitle:"The Science of Getting Better Suggestions",                  difficulty:"Advanced",    audience:"both",      duration:"25 min", summary:"Master the principles of prompt engineering — context, specificity, examples, and constraints — to dramatically improve Copilot suggestion quality.", keyPoints:["CSPEC: Context, Specificity, Pattern, Examples, Constraints","Vague prompts get vague results — be specific about inputs and outputs","Show the expected shape with a short example","Constraints (no external libs, thread-safe) dramatically improve quality","Iterative prompting is normal — refine until you get what you need"], links:[{text:"Prompt Engineering for Copilot",url:"https://docs.github.com/en/copilot/using-github-copilot/prompt-engineering-for-github-copilot"}] },
  { id:31, day:31, week:5, title:"Copilot Agent Mode & Autonomous Tasks",          subtitle:"Multi-Step Task Execution Across Files",                     difficulty:"Advanced",    audience:"both",      duration:"25 min", summary:"Use Copilot's Agent Mode to execute complex, multi-step tasks that span multiple files — creating features, refactoring modules, and fixing cross-cutting bugs.", keyPoints:["Agent mode edits multiple files in a single coordinated operation","Describe the task at a feature level — Copilot plans the steps","Review the diff for every file before accepting changes","Start with smaller, scoped tasks to build confidence in Agent mode","Agent mode works best with well-structured codebases and clear architecture"], links:[{text:"Copilot Agent Mode",url:"https://docs.github.com/en/copilot/using-github-copilot/using-copilot-edits"}] },
  { id:32, day:32, week:5, title:"GitHub Copilot Extensions",                      subtitle:"Extending Copilot with Domain-Specific Plugins",             difficulty:"Advanced",    audience:"both",      duration:"18 min", summary:"Learn about GitHub Copilot Extensions — how to use existing marketplace extensions and understand how to build custom ones for specialized domains.", keyPoints:["@github is the most powerful built-in Copilot extension","Third-party extensions (@docker, @azure) add specialized knowledge","Install extensions from GitHub Marketplace","Organizations can build internal extensions using GitHub Apps","Extensions use @ prefix followed by extension name in Chat"], links:[{text:"About Copilot Extensions",url:"https://docs.github.com/en/copilot/building-copilot-extensions/about-building-copilot-extensions"},{text:"Copilot Extensions Marketplace",url:"https://github.com/marketplace?type=apps&copilot_app=true"}] },
  { id:33, day:33, week:5, title:"Copilot in GitHub Actions & CI/CD",              subtitle:"AI-Powered Workflows, Pipeline Fixes & PR Automation",       difficulty:"Advanced",    audience:"both",      duration:"20 min", summary:"Use Copilot to generate GitHub Actions workflows, fix failing CI pipelines, and automate pull request review tasks.", keyPoints:["Describe the full CI/CD requirements in natural language","Paste failing step errors + workflow YAML to get fixes","GitHub.com Copilot PR summaries and reviews are built-in features","Ask for secret management best practices (never hardcode secrets)","Ask for parallelization and caching opportunities to optimize pipelines"], links:[{text:"GitHub Actions Docs",url:"https://docs.github.com/en/actions"}] },
  { id:34, day:34, week:5, title:"Code Review with Copilot",                       subtitle:"AI-Powered Review Comments, Security Analysis & Style",      difficulty:"Advanced",    audience:"both",      duration:"18 min", summary:"Leverage Copilot as a first-pass code reviewer — catching bugs, security issues, style violations, and performance concerns before human review.", keyPoints:["Use Copilot as a first-pass reviewer before submitting PRs","Ask targeted review questions: security, performance, style, correctness","GitHub.com PR review feature (Copilot Enterprise) adds inline comments","Paste git diffs into Chat for review without opening the full editor","@workspace reviews check consistency with existing codebase patterns"], links:[{text:"Copilot Code Review",url:"https://docs.github.com/en/copilot/using-github-copilot/code-review/using-copilot-code-review"}] },
  { id:35, day:35, week:5, title:"Multi-File Context & Large Codebase Navigation", subtitle:"@workspace, Semantic Search & Code Understanding at Scale",  difficulty:"Advanced",    audience:"both",      duration:"20 min", summary:"Strategies for working effectively with Copilot in large codebases — navigating, understanding, and modifying code across dozens of interconnected files.", keyPoints:["@workspace searches the entire project and returns relevant code","Ask Copilot to trace data flows through the codebase","Request Mermaid diagrams to visualize architecture","Ask impact analysis questions before making changes","Copilot accelerates onboarding to unfamiliar codebases dramatically"], links:[{text:"@workspace Context",url:"https://docs.github.com/en/copilot/github-copilot-chat/copilot-chat-in-ides/copilot-chat-context"}] },

  // Week 6: Enterprise & Best Practices
  { id:36, day:36, week:6, title:"GitHub Copilot for Business & Enterprise",       subtitle:"Team Management, Policies & Organization Features",          difficulty:"Advanced",    audience:"both",      duration:"18 min", summary:"Overview of GitHub Copilot Business and Enterprise plans — admin controls, usage policies, IP indemnification, and organization-wide deployment.", keyPoints:["Business plan adds admin controls, usage policies, and IP indemnification","Enterprise plan adds PR summaries, github.com integration, and fine-tuning","Admins can restrict Copilot per repo, team, or organization","Content exclusions prevent Copilot from reading sensitive files","IP indemnification only applies to Business and Enterprise plans"], links:[{text:"Copilot Business Docs",url:"https://docs.github.com/en/copilot/managing-copilot/managing-copilot-for-your-enterprise"}] },
  { id:37, day:37, week:6, title:"Security & Privacy Considerations",              subtitle:"What Data Copilot Sends, Retention & Compliance",            difficulty:"Advanced",    audience:"both",      duration:"20 min", summary:"Understand what data GitHub Copilot transmits, how it's used, data retention policies, and how to configure Copilot for privacy-sensitive environments.", keyPoints:["Copilot sends cursor context + open tabs — not your whole codebase","Business/Enterprise plans do not use your code for model training","Use content exclusions to protect .env and secrets files","GitHub Copilot is SOC 2 Type II certified; HIPAA available for Enterprise","Never paste real passwords, tokens, or PII into Copilot prompts"], links:[{text:"Copilot Privacy Statement",url:"https://docs.github.com/en/site-policy/privacy-policies/github-copilot-business-privacy-statement"},{text:"Copilot Trust Center",url:"https://resources.github.com/copilot-trust-center/"}] },
  { id:38, day:38, week:6, title:"Measuring Productivity & ROI",                   subtitle:"Copilot Metrics, Acceptance Rates & Business Value",          difficulty:"Advanced",    audience:"both",      duration:"15 min", summary:"Learn how to measure Copilot's impact on developer productivity using the Copilot Metrics API, VS Code telemetry, and organizational surveys.", keyPoints:["Copilot Metrics API tracks acceptance rate, lines accepted, active users","Industry benchmark: 25-30% suggestion acceptance rate","GitHub research: 55% faster task completion on average","Measure both quantitative (metrics) and qualitative (surveys) impact","ROI = time saved x developer cost - subscription cost"], links:[{text:"Copilot Metrics API",url:"https://docs.github.com/en/rest/copilot/copilot-metrics"},{text:"GitHub Copilot Research",url:"https://github.blog/2022-09-07-research-quantifying-github-copilots-impact-on-developer-productivity-and-happiness/"}] },
  { id:39, day:39, week:6, title:"Integrating Copilot into Team Workflows",        subtitle:"Onboarding, Standards & Cultural Adoption",                  difficulty:"Advanced",    audience:"both",      duration:"18 min", summary:"A practical guide to rolling out GitHub Copilot across an engineering team — training, standards, pair programming culture, and avoiding common adoption pitfalls.", keyPoints:["Phased rollout: champions → pilot → broad → continuous improvement","Define clear team standards for Copilot use before broad rollout","copilot-instructions.md becomes your team's shared knowledge base","Pair Copilot with code review — never skip review of AI-generated code","Track adoption and satisfaction with regular retrospectives"], links:[{text:"GitHub Skills: Copilot",url:"https://skills.github.com/"},{text:"Managing Copilot in Organizations",url:"https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization"}] },
  { id:40, day:40, week:6, title:"Common Pitfalls & How to Avoid Them",            subtitle:"Anti-Patterns, Over-Reliance & Critical Thinking",           difficulty:"Intermediate", audience:"both",      duration:"15 min", summary:"The most common mistakes developers and testers make with GitHub Copilot, and practical strategies to use it as an amplifier rather than a crutch.", keyPoints:["Always read every suggestion — plausible-looking code can be wrong","Copilot can hallucinate function names and API signatures","Run /tests on generated code — treat it like any other code review","Security-critical paths require manual review, always","Keep copilot-instructions.md up to date as conventions evolve"], links:[{text:"Responsible Use of Copilot",url:"https://docs.github.com/en/copilot/responsible-use-of-github-copilot-features"}] },
  { id:41, day:41, week:6, title:"Content Exclusions & Admin Controls",            subtitle:"Protecting Sensitive Files and Enforcing Policies",          difficulty:"Advanced",    audience:"both",      duration:"12 min", summary:"Configure content exclusions to prevent Copilot from reading sensitive files, and use admin controls to enforce organization-wide Copilot policies.", keyPoints:["Content exclusions prevent Copilot from reading sensitive files","Configure with glob patterns: **/.env, **/secrets/**, *.pem","Exclusions are enforced for all organization members","Duplication filter should stay ON for copyright safety","Admin controls are only available on Business and Enterprise plans"], links:[{text:"Content Exclusions",url:"https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/managing-github-copilot-features-in-your-organization/configuring-content-exclusions-for-github-copilot"}] },
  { id:42, day:42, week:6, title:"The Future of GitHub Copilot",                   subtitle:"What's Next: Models, Agents, and the AI-Native IDE",          difficulty:"Advanced",    audience:"both",      duration:"15 min", summary:"A look at the roadmap for GitHub Copilot — multi-model support, agentic workflows, MCP integration, and what the AI-native development future looks like.", keyPoints:["Multi-model: choose between GPT-4o, Claude, Gemini, and o1/o3","MCP integration connects Copilot to external data sources and tools","Copilot Coding Agent can take GitHub Issues and open PRs autonomously","The developer role shifts from writer to director and reviewer","The quality of your prompts and reviews becomes your key skill"], links:[{text:"Copilot Multi-Model",url:"https://docs.github.com/en/copilot/using-github-copilot/ai-models/changing-the-ai-model-for-github-copilot-chat"},{text:"GitHub Next",url:"https://githubnext.com/"}] },
];

export const WEEKS = [
  { week:1, title:"Getting Started",                color:"#2563eb" },
  { week:2, title:"Core Features",                  color:"#7c3aed" },
  { week:3, title:"For Developers",                 color:"#059669" },
  { week:4, title:"For Testers",                    color:"#d97706" },
  { week:5, title:"Advanced Features",              color:"#dc2626" },
  { week:6, title:"Enterprise & Best Practices",    color:"#0891b2" },
];

/**
 * Returns which topic (day) to send based on the schedule start date.
 * Days cycle back to Day 1 after Day 42 completes.
 */
export function getTodaysTopic(startDateStr) {
  const start = new Date(startDateStr);
  const now   = new Date();
  start.setHours(0,0,0,0);
  now.setHours(0,0,0,0);
  const elapsed = Math.floor((now - start) / (1000 * 60 * 60 * 24));
  const dayIndex = elapsed % TOPICS.length; // cycles after day 42
  return TOPICS[dayIndex];
}
